language: node_js
node_js: node
script: yarn fix && yarn run build -- --release
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

before_deploy: yarn global add babel-cli babel-core && yarn add --dev babel-preset-env babel-preset-flow babel-preset-react babel-preset-stage-2

deploy:
  provider: script
  script: yarn deploy
