language: node_js
node_js: node
script: yarn fix && yarn run build -- --release
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

deploy:
  provider: script
  script: yarn install --production=false && yarn deploy
