language: node_js

node_js:
  - 'stable'
  - '6'

branches:
  only:
  - master
  - "/v\\d\\./"

env:
  - CXX=g++-4.8

cache:
  directories:
  - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn lint

deploy:
  provider: script
  script: deploy
  on:
    branch: master